<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="QuanTriTaiKhoan.aspx.cs" Inherits="T3K22.Quan_tri.QuanTriTaiKhoan" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            Trang quản trị tài khoản<br />
            <asp:GridView ID="grvhienthi" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            </asp:GridView>
            <br />
            Tên đăng nhập<asp:TextBox ID="txttim" runat="server"></asp:TextBox>
            <br />
            <asp:Button ID="btntim" runat="server" Text="Tìm" OnClick="btntim_Click" />
        </div>
    </form>
</body>
</html>
